title: NeurIPS Meetup Japan 2021
description:

event_time: TBD
event_venue: TBD
event_description: Hello!
register_link: https://www.google.com

contact: "@"
copyright: NeurIPS Meetup Japan

timezone: Asia/Tokyo

collections:
  - events
